### ISSUE TITLE
Crash and burn

### ISSUE THREAD

**Issue by asteinh** [meco-group/QRoboticsCenter#6]
Numerous reports on crashing/frozen QRC v6.0.0 on Windows (10, maybe also others). Cannot reproduce, probably only appears after some time/use.

Need reproducible faults + conditions to effectively debug.

**Comment by asteinh** [comment]
First clue contributed by @ljbs, *active flag* as shown [here](https://user-images.githubusercontent.com/14937496/70211382-36e67580-1735-11ea-9b9f-88431edbb288.png) seems missing when frozen. When using `Ctrl+X`, QRC crashes.

**Comment by ljbs** [comment]
A log file from a user with the Arduino connected to COM5, until it crashes after pressing Ctrl+X: [log.txt](https://github.com/meco-group/QRoboticsCenter/files/3932510/log.txt).
A lot file of the same procedure on a PC that does not give any issues: [log_laurens.txt](https://github.com/meco-group/QRoboticsCenter/files/3932524/log_laurens.txt). 
There is a significant difference in the logged output - the former clearly detects heartbeats several times and encounters timeouts, whereas the latter log is rather compact.

**Comment by ljbs** [comment]
Reported again on October 22. Approach (discussed with @danieleR3, @ha7ilm @tmmsartor):
- students with issues on Windows run QRC from `WinDbg` and send the log file once the bug occurs
- the existing `develop` build (Qt 5.11.3) or a new `develop` build (Qt 5.15.1) are started from Qt Creator in debug mode on the PC of the student(s) that have issues in order to track down the issue
- investigate whether the problem still occurs with a more recent Qt version (Qt 5.15.1); if not, then release this build as a new major release

**Comment by ljbs** [comment]
`WinDbg` output: [log.txt](https://github.com/meco-group/QRoboticsCenter/files/5433517/log.txt)
Crash (on Windows) seems to happen in `QAction::setChecked()`. Invalid pointer leading to a segfault? This is the first suspect:

https://github.com/meco-group/QRoboticsCenter/blob/2590fc21228580586e1e5504046e68162b9bcc85/src/QtModules/QRobotOverview/src/QRobotWidgets/qrobotwindow.cpp#L75

@ha7ilm noticed during decompilation that the issue seems to occur in a `QList`, confirming this guess.

**Comment by ljbs** [comment]
**Hotfix 867abef58edb0c521653d08af5b5918d727ef8e8 was reported by the students to resolve this issue. Finally!**

Immediately took the opportunity to upgrade to Qt 5.15.1 (5.14.2 on Linux). 
Windows builds are now with MinGW instead of VS. 
Released as [v6.1.0](https://github.com/meco-group/QRoboticsCenter/releases/tag/v6.1.0)
